defaults:
  - load_dataframe: default
  - combine_columns: combine
  - aggregate_columns: aggregate
  - rename_columns: rename
  - reset_index: reset
  - fillna: fillna
  - normalize: normalize
  - segment: segment
  - replace_whitespace: whitespace
  - replace_regex: regex
  - filter_length: default
  - drop_duplicates: drop
  - save_samples: samples
  - save_dataframe: default
  - concat_dataframes: default
  - split_dataframe: default
  - eval_columns: default
  - melt: default
  - split_sampling: default
  - sampling: default
  - filter_query: default
  - merge_dataframe: default
  - top_values: default
  
_target_: ekorpkit.pipelines.pipe.process_dataframe
_pipeline_:
  - load_dataframe
  - save_dataframe
data_dir: ${oc.select:..data_dir, ''} 
data_file: ${oc.select:..data_file, ''}
apply_to: ${oc.select:..column_info.keys.text, text}
use_batcher: true
verbose: ${oc.select:..verbose, true}
