defaults:
  - default

_target_: ekorpkit.preprocessors.tokenizer.MecabTokenizer
mecab:
  userdic_path: ${dir.resource}/dictionaries/mecab/ekon_v1.dic
  backend: mecab-python3
  verbose: ${oc.select:..verbose, false}
