_target_: ekorpkit.info.base.ColumnInfo
keys:
  id: id
  text: text
  timestamp: timestamp
  split: split
columns:
  id: ${oc.select:..keys.id,id}
  text: ${oc.select:..keys.text,text}
  merge_meta_on: ${oc.select:..id}
  timestamp: ${oc.select:..timestamp.key,timestamp}
data:
  id: int
  text: str
meta:
timestamp:
  key:
  format:
  params:
datetime:
  key:
  format:
  params:
segment_separator: ${oc.select:..segment_separator, '\n\n'}
