defaults:
  - default

_target_: ekorpkit.datasets.corpora.Corpora
corpora:
data_dir: ${dir.corpus}
use_name_as_subdir: true
auto:
  load: false
verbose: ${oc.select:..verbose, true}
collapse_ids: false
column_info:
  _keys_:
    corpus: corpus
