defaults:
  - /column_info: default

_target_: ekorpkit.corpora.corpus.Corpus
name: ${oc.select:.builtin.name, null}
data_dir: ${oc.select:.builtin.data_dir, ${dir.corpus}}
metadata_dir:
filetype: ${oc.select:.builtin.filetype, null}
autoload: true
automerge: false
verbose: ${oc.select:..verbose, true}
use_name_as_subdir: true
