defaults:
  - /module: stable_diffusion
  - /path: stable_diffusion
  - batch: default
  - model: default
  - imagine: default
  - collage: default

_target_: ekorpkit.models.art.stable.StableDiffusion
autoload: false
name: stable-diffusion
verbose: ${oc.select:..verbose, false}
device: "cuda:7"
hf_user_access_token:
