# @package _global_
defaults:
  - _self_
  - about: default
  - cmd: default
  - corpus: _loader
  - dataset: _loader
  - dir: default
  - env: default
  - mode: default
  - model: default
  - project: default
  - task: _default

  - override hydra/help: help
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  searchpath:
    - ${oc.env:EKORPKIT_CONFIG_DIR,${check_path:./config,pkg://ekorpkit/conf}}
