# @package _global_
_config_:
_target_:
defaults:
  - _self_
  - about: default
  - cmd: default
  - corpus: _loader
  - dataset: _loader
  - dir: default
  - env: default
  - mode: default
  - model: default
  - project: default
  - task: _default

  - override hydra/help: help
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

app_name: ${about.app.name}
