# @package _global_
_key_:
_target_:
defaults:
  - _self_
  - about: default
  - cmd: default
  - dir: default
  - env: default
  - mode: default
  - corpus: _loader
  - dataset: _loader
  - task: _default
  - model: null
  - project: null
  - tokenizer: null

  - override hydra/help: help
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

app_name: ${about.app.name}
project: ${app_name}
