# @package _global_
_target_: ekorpkit.cli.about
defaults:
  - _self_
  - about: default
  - cmd: null
  - dir: default
  - env: default
  - mode: default
  - corpus: _loader
  - dataset: _loader
  - task: _default
  - model: null
  - project: null
  - tokenizer: null

  - override hydra/help: help

app_name: ${about.app.name}
project: ${app_name}
