defaults:
  - /fetch: corpus
  - /info: corpus_build
  - /pipeline: corpus_build_pipeline

_target_: ekorpkit.io.fetch.build.DatasetBuilder
name:
data_dir: ${dir.corpus}/${.name}
# data_dir: ${dir.archive}/datasets/lmdata/${.name}
filetype: .parquet
segment_separator: \n\n
sentence_separator: \n
verbose: ${oc.select:..verbose, true}
