defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /preprocessor/segmenter: kss

name: aida_paper
fullname: AIDA Papers Fulltext Corpus
description: AIDA Papers Fulltext Corpus 
license: Attribution-NonCommercial (CC-By-NC v3)
homepage: https://aida.kisti.re.kr
lang: ko
category: academic
domain: science
version: 1.0.0
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    abstract: str
    text: str
  meta:
    id: int
    doc_id: str
    title: str
    year: str
    authors: str
    journal: str
    keywords: str

io:
  data_dir: ${dir.archive}/datasets/source/aida
  data_sources: 
    train: aida_papers.zip
  loader:    
    multiprocessing_at: parse_json
    filetype: json
    data:
      field:
      item:
        doc_id: doc_id
        title: title.ko
        year: year
        authors: authors
        journal: journal.ko
        keywords: keywords.ko
        abstract: abstract.ko
        text: body_text[*].text
      item_separator: '\n\n'

pipeline:
  _transform_:
    - combine_columns
    - reset_index
  _preprocess_:  
    - normalize
    - segment
    - filter_length
    - drop_duplicates

  combine_columns:
    into: text
    columns:
      - abstract
      - text
    separator: '\n\n'
  filter_length:
    min_length: 10
