defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /preprocessor/segmenter: kss

name: aihub_koen_formal
fullname: AiHub Formal Traslation
description: AIHub Korean to English Formal Translation Corpus
license: Attribution-NonCommercial (CC-By-NC v3)
homepage: https://aihub.or.kr
lang: ko
category: formal
domain: mixed
version: 1.0.0
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    text: str
  meta:
    id: int
    sid: str
    field: str
    difficulty: str
    english: str

io:
  data_dir:  ${dir.archive}/datasets/source/aihub/전문분야 한영 말뭉치
  data_sources: 
    train: Training/ko2en_training_json.zip
    test: Validation/ko2en_validation_json.zip
  loader:
    multiprocessing_at: parse_json
    filetype: json
    data:
      field: 
      item:
        sid: sid
        field: 분야
        text: 한국어
        english: 영어
        difficulty: 난이도

pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
