defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /preprocessor/segmenter: kss
  - override /io/loader/parser: json_to_list

name: aihub_law_case
fullname: AiHub Law Knowledge Base
description: AIHub/KB/Law
license: Attribution-NonCommercial (CC-By-NC v3)
homepage: https://aihub.or.kr
lang: ko
category: formal
domain: law
version: 1.0.0
column_info:
  columns:
    id: id
    text: text 
  data:
    id: int
    text: str
  meta:
    id: int
    case_number: str
    case_name: str
    abstract: str
    precedent: str
    jugement_note: str

io:
  data_dir:  ${dir.archive}/datasets/source/aihub/법령지식
  data_sources:
    train: 법령지식_관련판례(Json).zip
  loader:
    multiprocessing_at: parse_data
    filetype: json
    data:
      field:
      item:
        case_number: '"http://www.aihub.or.kr/kb/law/caseNumber"[*].value' 
        case_name: '"http://www.aihub.or.kr/kb/law/caseName"[*].value'
        abstract: '"http://www.aihub.or.kr/kb/law/judgementAbstract"[*].value'
        precedent: '"http://www.aihub.or.kr/kb/law/precedentText"[*].value'
        jugement_note: '"http://www.aihub.or.kr/kb/law/judgementNote"[*].value'

pipeline:
  _transform_:
    - combine_columns
    - reset_index
  _preprocess_:  
    - normalize
    # - segment
    - filter_length
    - drop_duplicates

  filter_length:
    min_length: 10
  combine_columns:
    into: text
    columns:
      - abstract
      - precedent
      - jugement_note
    separator: '\n'
