defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /preprocessor/segmenter: kss
  - override /io/loader/parser: json_to_list

name: aihub_law_kb
fullname: AiHub Law Knowledge Base
description: AIHub/KB/Law
license: Attribution-NonCommercial (CC-By-NC v3)
homepage: https://aihub.or.kr
lang: ko
category: formal
domain: law
version: 1.0.0
column_info:
  columns:
    id: id
    text: 
      - text
  data:
    id: int
    text: str

io:
  data_dir:  ${dir.archive}/datasets/source/aihub/법령지식
  data_sources: 
    train: 
      - 법령지식_층간소음(Json).zip 
      - 법령지식_교통사고(Json).zip
      - 법령지식_창업인허가(Json).zip
  loader:
    multiprocessing_at: parse_data
    filetype: json
    data:
      field: 
      item:
        text: '"http://www.aihub.or.kr/kb/law/fullText"[*].value'
  preprocess_info:
    normalize: true
    segment: true
    min_text_length: 10

pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
    # - segment
    - filter_length
    - drop_duplicates

  filter_length:
    min_length: 10
