defaults:
  - _build
  - /io/fetcher: bok
  - /preprocessor/normalizer: formal_ko
  - override /io/loader: dataframe

name: bok_minutes
fullname: BOK MPB Minutes
lang: ko
category: formal
domain: econ
description: BOK Minutes Corpus
license: "Bank of Korea"
homepage: https://www.bok.or.kr
version: 1.0.0
column_info:
  data:
    id: int
    text: str
  meta:
    id: int
    mdate: str
    rdate: str
    filename: str


io:
  data_sources: 
    train: ${..fetcher.output_file}

pipeline:
  _transform_:
    - combine_columns
    - aggregate_columns
    - reset_index
  _preprocess_:
    - fillna
    - normalize
    # - segment
    - filter_length
    - drop_duplicates

  combine_columns:
    into: text
    columns:
      - section
      - text
    separator: '\n'
  aggregate_columns:
    onto: text
    groupby:
      - mdate
      - rdate
      - filename
    separator: '\n\n'
