defaults:
  - _build
  - /fetch/downloader: edgar
  - /preprocessor/normalizer: formal_en

name: edgar
fullname: EDGAR Corpus
description: 'EDGAR-CORPUS: Billions of Tokens Make The World Go Round (10-K filings)'
license: Open Access
homepage: https://zenodo.org/record/5589195 
version: 1.0.0
lang: en
category: formal
domain: econ
column_info:
  keys:
    id: id
    text: text
  data:
    id: int
    text: str
  meta:
    id: int
    cik: str
    company: str
    filing_type: str
    filing_date: str
    period_of_report: str
    sic: str
    state_of_inc: str
    state_location: str
    fiscal_year_end: str
    filing_html_index: str
    htm_filing_link: str
    complete_text_filing_link: str
    filename: str

fetch:
  data_sources:
    train: '*.zip'
  loader:
    # decode_before_parse: false
    data:
      field: 
      item:
        cik: cik
        company: company
        filing_type: filing_type
        filing_date: filing_date
        period_of_report: period_of_report
        sic: sic
        state_of_inc: state_of_inc
        state_location: state_location 
        fiscal_year_end: fiscal_year_end
        filing_html_index: filing_html_index
        htm_filing_link: htm_filing_link
        complete_text_filing_link: complete_text_filing_link
        filename: filename
        text: 
          - item_1
          - item_1A
          - item_1B
          - item_2
          - item_3
          - item_4
          - item_5
          - item_6
          - item_7
          - item_7A
          - item_8
          - item_9
          - item_9A
          - item_9B
          - item_10
          - item_11
          - item_12
          - item_13
          - item_14
          - item_15
      segment_separator: '\n\n'

pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
    - filter_length
    # - segment
    - drop_duplicates