defaults:
  - _build
  - /fetch/downloader: fomc
  - /preprocessor/normalizer: formal_en
  - /preprocessor/segmenter: pysbd
  - override /fetch/loader: csv

name: fomc
fullname: Federal Open Market Committee (FOMC) Corpus
lang: en
category: formal
domain: econ
description: FOMC
license: 
homepage: https://www.federalreserve.gov
version: 1.0.0
column_info:
  keys:
    id: id
    text: text
  data:
    id: int
    text: str
  meta:
    id: int
    # content_type: str
    date: str
    speaker: str
    title: str

fetch:
  data_sources:
    train: '*.csv'

pipeline:        
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
    - segment
    # - filter_length
    - drop_duplicates
