defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /preprocessor/segmenter: kss

name: nikl_spoken
fullname: NIKL Spoken Text Corpus
description: National Institute of the Korean Language Corpus - Spoken
license: Korea Open Government License, Category 4
homepage: https://corpus.korean.go.kr
version: 1.0.0
lang: ko
category: spoken
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    text: str
  meta:
    id: int
    doc_id: str
    title: str
    author: str
    publisher: str
    date: str
    category: str
io:
  data_dir: ${dir.archive}/datasets/source/nikl
  data_sources: 
    train: 
      - NIKL_SPOKEN_v1.2.zip
  loader:
    multiprocessing_at: _load_archive
    filetype: json
    data:
      field: document
      item:
        doc_id: id
        title: metadata.title
        author: metadata.author
        publisher: metadata.publisher
        date: metadata.date
        text: 
          - utterance[*].form
      item_separator: '\n'
    meta:
      field: metadata
      item:
        category: category

pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
    # - segment
    - filter_length
    - drop_duplicates

  filter_length:
    min_length: 10
