defaults:
  - _build
  - /preprocessor/normalizer: formal_en
  - /preprocessor/segmenter: pysbd
  - /io/fetcher: pathobook
  - override /io/loader: dataframe

name: pathobook
lang: en
category: formal
domain: bio
fullname: Pathology Book Corpus
description: Pathology Textbook Corpus
license: 
homepage: 
version: 1.0.0
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    text: str
  meta:
    id: int
    chapter: str

io:
  data_dir:  ${dir.dataset}/source/${.name}
  data_sources: 
    train: ${..fetcher.output_file}


pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
    - filter_length
    - segment
