defaults:
  - _build
  - /preprocessor/normalizer: formal_en
  - /preprocessor/segmenter: pysbd_filter_pl
  - override /io/loader: the_pile

available: false
name: stackexchange
lang: en
category: informal
domain: tech
fullname: The Stack Exchange Data Dump
description: 'The Stack Exchange Data Dump contains an anonymized set of all user-contributed content on the Stack Exchange network, a popular collection of websites centered around user-contributed ques- tions and answers.'
license: MIT License
homepage: https://archive.org/details/stackexchange
version: 1.0.0
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    text: str

io:
  data_dir: ${dir.archive}/datasets/source/the_pile
  data_sources: 
    train: train
    test: test
    valid: valid
  loader:
    name: StackExchange

pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    # - normalize
    # - filter_length
    - segment
    - drop_duplicates

