defaults:
  - _build
  - /preprocessor/normalizer: formal_en
  - /preprocessor/segmenter: pysbd_merge_segment
  - override /io/loader: the_pile

name: youtube_subtitles
lang: en
category: informal
domain: mixed
fullname: YouTube Subtitles
description: 'The YouTube Subtitles dataset is a parallel corpus of text gathered from human generated closed- captions on YouTube. In addition to providing mul- tilingual data, Youtube Subtitles is also a source of educational content, popular culture, and natural dialog.'
license: MIT License
homepage: https://youtube.com
version: 1.0.0
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    text: str


io:
  data_dir: ${dir.archive}/datasets/source/the_pile
  data_sources: 
    train: train
    test: test
    valid: valid
  loader:
    name: YoutubeSubtitles

pipeline:
  _transform_:
    - reset_index
  _preprocess_:  
    - normalize
    - filter_length
    - segment
    - drop_duplicates

