ekorpkit: ${__ekorpkit_path__:}
home: ${__home_path__:}
workspace: ${.home}/.ekorpkit
project: ${.workspace}/projects/${project}
data: ${.workspace}/data
log: ${.project}/logs
tmp: ${.data}/tmp
cache: ${.tmp}/.cache
archive: ${.data}/archive
runtime: ${oc.select:hydra:runtime.cwd, .}
model: ${.data}/models
output: ${.data}/outputs
dataset: ${.data}/datasets
corpus: ${.dataset}/corpus
resource: ${.ekorpkit}/resources
