ekorpkit: ${__ekorpkit_path__:}
home: ${__home_path__:}
workspace: ${.home}/.ekorpkit
project: ${.workspace}/projects/${project}
data: ${.workspace}/data
tmp: ${.workspace}/.tmp
cache: ${.workspace}/.cache
log: ${.project}/logs
archive: ${.data}/archive
model: ${.data}/models
output: ${.data}/outputs
dataset: ${.data}/datasets
corpus: ${.dataset}/corpus
resource: ${.ekorpkit}/resources
runtime: ${oc.select:hydra:runtime.cwd, .}
