archive: ${.data}/archive
cache: ${.workspace}/.cache
corpus: ${.dataset}/corpus
data: ${.workspace}/data
dataset: ${.data}/datasets
ekorpkit: ${__ekorpkit_path__:}
home: ${__home_path__:}
log: ${.project}/logs
model: ${.data}/models
output: ${.project}/outputs
project: ${.workspace}/projects/${project}
resource: ${.ekorpkit}/resources
runtime: ${oc.select:hydra:runtime.cwd, .}
tmp: ${.workspace}/.tmp
workspace: ${.home}/.ekorpkit
