defaults:
   - /pipeline: corpus_task

_target_: ekorpkit.corpora.loader.do_corpus_tasks
name: export_processed
merge_metadata: true
verbose: ${oc.select:..verbose, true}

pipeline:
  _pipeline_:
    - filter_query
    - filter_length
    - explode_splits
    - save_dataframe
  name: ${..name}
  verbose: ${oc.select:..verbose, true}
  apply_to: 
    - text
  filter_query:
    query: chapter == '21'
  filter_length:
    min_length: 15  
  explode_splits:
    id_key: id
    split_key: sent_id
    separator: '\n'
  save_dataframe:
    task_dir: corpus_filtered
