defaults:
  - _default

_target_: ekorpkit.io.fetch.fomc.build_fomc
name: ${oc.select:..name, fomc}
from_year: 1990
contents:
  - content_type: fomc_statement
    _target_: ekorpkit.io.fetch.fomc.Statement
  - content_type: fomc_minutes
    _target_: ekorpkit.io.fetch.fomc.Minutes
  # - content_type: fomc_beigebook
  #   _target_: ekorpkit.io.fetch.fomc.BeigeBook
  - content_type: fomc_speech
    _target_: ekorpkit.io.fetch.fomc.Speech
  - content_type: fomc_testimony
    _target_: ekorpkit.io.fetch.fomc.Testimony
  - content_type: fomc_meeting_script
    _target_: ekorpkit.io.fetch.fomc.MeetingScript
  - content_type: fomc_press_conf
    _target_: ekorpkit.io.fetch.fomc.PresConfScript
base:
  _target_: ekorpkit.io.fetch.fomc.FOMC
  content_type: fomc_base
fomc:
  base_url: https://www.federalreserve.gov
  calendar_url: ${.base_url}/monetarypolicy/fomccalendars.htm
  segment_separator: '\n\n'
  verbose: ${oc.select:..verbose, false}
  force_download: false
  num_workers: ${..num_workers}
  output_dir: ${..output_dir}
  chair:
    - surname: Volcker
      first_name: Paul
      from_date: "1979-08-06"
      to_date: "1987-08-10"
    - surname: Greenspan
      first_name: Alan
      from_date: "1987-08-11"
      to_date: "2006-01-31"
    - surname: Bernanke
      first_name: Ben
      from_date: "2006-02-01"
      to_date: "2014-01-31"
    - surname: Yellen
      first_name: Janet
      from_date: "2014-02-03"
      to_date: "2018-02-03"
    - surname: Powell
      first_name: Jerome
      from_date: "2018-02-05"
      to_date: ${today:%Y-%m-%d}

  recessions:
    - name: Dot-com Bubble
      description: Dot-com bubble
      source: https://en.wikipedia.org/wiki/Dot-com_bubble
      from_date: 2000-03
      to_date: 2002-10
      format: "%Y-%m"
    - name: Financial Crisis
      description: Financial crisis of 2007-2008
      source: https://en.wikipedia.org/wiki/Financial_crisis_of_2007-2008
      from_date: 2007-04
      to_date: 2009-03
      format: "%Y-%m"
    - name: Euro Debt Crisis
      description: European debt crisis
      source: https://en.wikipedia.org/wiki/European_debt_crisis
      from_date: 2010-09
      to_date: 2012-09
      format: "%Y-%m"
    - name: Chinese Crisis
      description: 2015-16 Chinese stock market turbulence
      source: https://en.wikipedia.org/wiki/2015-2016_Chinese_stock_market_turbulence
      from_date: 2015-01
      to_date: 2016-06
      format: "%Y-%m"
    - name: COVID-19
      description: COVID-19 Pandemic
      source: https://en.wikipedia.org/wiki/COVID-19_pandemic
      from_date: 2020-02
      to_date: 2022-02
      format: "%Y-%m"

  unconventionals:
    - name: QE1
      date: 2008-11-25
      description: QE1 announced
      unscheduled: true
      rate: 0.0
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: QE1+
      date: 2009-03-18
      description: QE1 expanded
      unscheduled: false
      rate: 0.25
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: QE2
      date: 2010-11-03
      description: QE2 announced
      unscheduled: false
      rate: 0.25
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: OT
      date: 2011-09-21
      description: Operation Twist announced
      unscheduled: false
      rate: 0.25
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: OT+
      date: 2012-06-20
      description: Operation Twist expanded
      unscheduled: false
      rate: 0.25
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: QE3
      date: 2012-09-13
      description: QE3 announced
      unscheduled: false
      rate: 0.25
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: QE3+
      date: 2012-12-12
      description: QE3 expanded
      unscheduled: false
      rate: 0.25
      rate_decision: -2
      rate_change: -0.5
      format: "%Y-%m-%d"
    - name: Tapering
      date: 2013-06-19
      description: Tapering announced
      unscheduled: false
      rate: 0.25
      rate_decision: 2
      rate_change: 1.0
      format: "%Y-%m-%d"
    - name: Tapering+
      date: 2013-12-18
      description: Tapering begins
      unscheduled: false
      rate: 0.25
      rate_decision: 2
      rate_change: 1.0
      format: "%Y-%m-%d"
    - name: QE3-
      date: 2014-10-29
      description: QE3 terminated
      unscheduled: false
      rate: 0.25
      rate_decision: 2
      rate_change: 0.5
      format: "%Y-%m-%d"
    - name: BSNorm
      date: 2017-06-14
      description: Signaled Balance Sheet Normalization
      unscheduled: false
      rate: 1.25
      rate_decision: 2
      rate_change: 0.5
      format: "%Y-%m-%d"
    - name: BSNorm+
      date: 2017-09-20
      description: Stated Balance Sheet Normalization Begins in Oct
      unscheduled: false
      rate: 1.25
      rate_decision: 2
      rate_change: 0.5
      format: "%Y-%m-%d"

  econ_series:
    # GDP is announced quarterly, the end of following month (preliminary)
    - id: GDPC1
      name: GDP
      title: Real GDP ($b)
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=4) / value.shift(4) * 100"
      relativedelta:
        months: 4
        days: -2
    - id: GDPPOT
      name: GDPPOT
      title: Potential GDP ($b)
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=4) / value.shift(4) * 100"
      relativedelta:
        months: 4
        days: -2
    # PCE is announced monthly, at the end of following month
    - id: PCEPILFE
      name: PCE
      title: PCE
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 2
        days: -1
    # CPI is announced monthly, around 10th of the following month
    - id: CPIAUCSL
      name: CPI
      title: CPI
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 9
    # Employment statistics is announced monthly, around 3rd of the following month
    - id: UNRATE
      name: UNEMP
      title: Unemployment Rate (%)
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 2
    # Employment statistics is announced monthly, around 3rd of the following month
    - id: PAYEMS
      name: EMP
      title: Employment (persons)
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 2
    # ISM PMI is areannounced monthly, around 1st of the following month
    - id: ISM/MAN_PMI
      name: PMI
      title: PMI
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 2
    # ISM NMI is areannounced monthly, around 1st of the following month
    - id: ISM/NONMAN_NMI
      name: NMI
      title: NMI
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 2
    # Retail Sales is announced monthly, around 15th of the following month
    - id: RRSFS
      name: RSALES
      title: Retail Sales {$m}
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 2
    # New Home Sales is announced monthly, around a week before the end of the following month
    - id: HSN1F
      name: HSALES
      title: New Home Sales {$m}
      expressions:
        - "value_diff_prev = value.diff() / value.shift(1) * 100"
        - "value_diff_year = value.diff(periods=12) / value.shift(12) * 100"
      relativedelta:
        months: 1
        days: 2
