defaults:
  - _default

_target_: ekorpkit.io.fetch.fred.Fred
api_key: ${oc.env:FRED_API_KEY,null}
name: 
function: get_series
series_id:
observation_start:
observation_end:
concat: false
merge: false
