_target_: ekorpkit.preprocessors.segmenter.SimpleSegmenter
language: en
clean: false
in_segment_separator: '\n\n'
in_sentence_separator: '\n'
out_segment_separator: '\n\n'
out_sentence_separator: '\n'
return_type: str
keep_segment: ${oc.select:..keep_segment, false}
chunk_size: ${oc.select:..chunk_size, 300}
chunk_overlap: ${oc.select:..chunk_overlap, false}
print_args: true