defaults:
  - _default

_target_: ekorpkit.io.fetch.fomc.build_fomc
compress: false
from_year: 1990
contents:
  - content_type: fomc_statement
    _target_: ekorpkit.io.fetch.fomc.Statement  
  - content_type: fomc_minutes
    _target_: ekorpkit.io.fetch.fomc.Minutes  
  # - content_type: fomc_beigebook
  #   _target_: ekorpkit.io.fetch.fomc.BeigeBook
  - content_type: fomc_speech
    _target_: ekorpkit.io.fetch.fomc.Speech
  - content_type: fomc_testimony
    _target_: ekorpkit.io.fetch.fomc.Testimony
  - content_type: fomc_meeting_script
    _target_: ekorpkit.io.fetch.fomc.MeetingScript  
  - content_type: fomc_press_conf
    _target_: ekorpkit.io.fetch.fomc.PresConfScript  
fomc:
  base_url: https://www.federalreserve.gov
  calendar_url: ${.base_url}/monetarypolicy/fomccalendars.htm
  segment_separator: '\n\n'
  verbose: true
  force_download: false
  num_workers: ${..num_workers}
  output_dir: ${..output_dir}
  compress: ${..compress}
  chair:
    columns: [Surname, FirstName, FromDate, ToDate]
    data:
      - [Greenspan, Alan, 1987-08-11, 2006-01-31]
      - [Bernanke, Ben, 2006-02-01, 2014-01-31]
      - [Yellen, Janet, 2014-02-03, 2018-02-03]
      - [Powell, Jerome, 2018-02-05, 2022-02-05]
