defaults:
  - /auto: default
  - /batch: default
  - /secret: default
  - /project: language-modeling
  - /path: _batch_
  - /dataset: huggingface
  - model: unigram
  - training: huggingface
  - exporting: default

_target_: ekorpkit.tokenizers.trainer.TokenizerTrainer
name: tokenizer-trainer
data:
  shuffle: true
