defaults:
  - /column_info: _build_simple
  - /io: _build_simple
  - /info: _build_dataset
  - /pipeline: _build_dataset
  - /auto: load

_target_: ekorpkit.datasets.build.DatasetBuilder
name:
category: general
data_dir: ${dir.dataset}/simple/${.name}
filetype: .parquet
verbose: ${oc.select:..verbose, true}

normalize:
  preprocessor:
    normalizer: ${oc.select:dataset.simple.preprocessor.normalizer,null}
segment:
  preprocessor:
    segmenter: ${oc.select:dataset.simple.preprocessor.segmenter,null}
