defaults:
  - /fetch: simple
  - /info: dataset_build
  - /pipeline: dataset_build_pipeline

_target_: ekorpkit.io.fetch.build.DatasetBuilder
name: 
category: general
data_dir: ${dir.dataset}/simple/${.name}
filetype: .csv
verbose: ${oc.select:..verbose, true}
