defaults:
  - /fetch: simple
  - /info: dataset_build
  - /pipeline: dataset_build

_target_: ekorpkit.io.fetch.build.DatasetBuilder
name:
category: general
data_dir: ${dir.dataset}/simple/${.name}
filetype: .csv
verbose: ${oc.select:..verbose, true}
autoload: true
