defaults:
  - /fetch: simple
  - /info: dataset_build
  - /pipeline: dataset_build

_target_: ekorpkit.io.fetch.build.DatasetBuilder
name:
category: general
data_dir: ${dir.dataset}/simple/${.name}
filetype: .csv
verbose: ${oc.select:..verbose, true}
autoload: true

normalize:
  preprocessor:
    normalizer: ${oc.select:dataset.simple.preprocessor.normalizer,null}
segment:
  preprocessor:
    segmenter: ${oc.select:dataset.simple.preprocessor.segmenter,null}
