defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /io/fetcher: dataframe

name: analystsent_kr
domain: econ
task: classification
lang: ko
column_info:
  columns:
    id: id
    text: text
  data:
    id: int
    seq: int
    labels: str
    text: str

io:
  data_sources:
    train: train.csv
    test: test.csv
    dev: dev.csv
  fetcher:
    output_file: analystsent_kr.csv
    pipeline:
      _pipeline_:
        - load_dataframe
        - rename_columns
        - drop_duplicates
        - replace
        - reset_index
        - split_sampling
      rename_columns:
        new_names:
          SEQ: seq
          SENTENCE: text
          TAG: labels
      replace:
        apply_to: labels
        parameters:
          to_replace:
            0: neutral
            1: positive
            -1: negative
      split_sampling:
        stratify_on: labels
        dev_size: 0.2
        test_size: 0.2
        unique_key: seq
        output_dir: ${..data_dir}
        train_file: train.csv
        test_file: test.csv
        dev_file: dev.csv

pipeline:
  _transform_:
  _preprocess_:
    - normalize
  normalize:
    preprocessor:
      normalizer: ${dataset.simple.preprocessor.normalizer}
