defaults:
  - /env: default
  - /path: __project__

project_name: ${oc.select:project_name,${oc.env:EKORPKIT_PROJECT_NAME,ekorpkit-project}}
task_name: default-task
project_root: ${.path.project}
workspace_root: ${oc.select:workspace_dir,${alt:${oc.env:EKORPKIT_WORKSPACE_ROOT,null},${.path.home}/.ekorpkit}}
description:
use_huggingface_hub: false
use_wandb: false
verbose: false
