defaults:
  - /method: general_function

apply_to: ${oc.select:..apply_to, ''}
function: replace
parameters:
  to_replace:
  value:
  limit:
  regex: false
  method:
verbose: ${oc.select:..verbose, true}

