_target_: ekorpkit.models.sentiment.Lexicon
name: kosac_polarity
fullname: The KOrean Sentiment Analysis Corpus
source: http://word.snu.ac.kr/kosac
lang: ko
ngram_delim: ;
lexicon_path: ${dir.resource}/lexicons/kosac/polarity.parquet
lexicon_features:
  - COMP
  - NEG
  - NEUT
  - None
  - POS
  - max.value
  - max.prop
word_key: ngram
ignore_pos: false
analyze:
  features:
  ngram_distiance_tolerance: 0
  ngram_delim: ${..ngram_delim}
