defaults:
  - _default
  - /pipeline: dataframe
  # - /preprocessor/normalizer: formal_en
  # - /preprocessor/segmenter: pysbd

_target_: ekorpkit.tasks.task.dataframe_tasks
name: dataframe_task
data_dir:
data_file:

pipeline:
  _pipeline_:
    # - load_dataframe
    # - normalize
    # - filter_length
    # - split_dataframe
    # - segment
    # - concat_dataframes
    # - drop_duplicates
    # - save_dataframe
  # save_dataframe:
  #   output_dir: ${dir.project}/dataframe/tmp
  #   output_file: ${..load_dataframe.data_file}
  # split_dataframe:
  #   num_splits: 10
  # filter_length:
  #   min_length: 30
  #   max_length: 10_000
  # drop_duplicates:
  #   apply_to:
  #     - text
  # segment:
  #   segmenter:
  #     merge_lines: true
  #     merge_level: article
  #     verbose: true
  #     max_split_length: 11_000
