defaults:
  - /method: chunk
  - segmenter: chunk

keep_segment: false
chunk_size: 300
chunk_overlap: false
apply_to: ${oc.select:..apply_to, text}
verbose: ${oc.select:..verbose, true}
use_batcher: ${oc.select:..use_batcher, true}