defaults:
  - default

_target_: ekorpkit.datasets.loader.Datasets
name: 
datasets:
data_dir: ${dir.dataset}/dataset
autorun:
  - load
  # - name: concatenate
  #   args:
  #     append_dataset_name: true
