defaults:
  - default

_target_: ekorpkit.datasets.loader.Datasets
name: 
data_dir: ${dir.dataset}/dataset
splits:
  train:
  dev:
  test:
column_info:
  keys:
    id: id
  data:
autorun:
  - load
  # - name: concatenate
  #   args:
  #     append_dataset_name: true
