defaults:
  - /column_info: default
  - /path: cache
  - /auto: load

_target_: ekorpkit.datasets.dataset.Dataset
name: ${oc.select:.builtin.name, null}
data_dir: ${dir.dataset}/dataset
filetype: ${oc.select:.builtin.filetype, .parquet}
use_name_as_subdir: true
verbose: ${oc.select:..verbose, true}
