name: ${oc.select:.builtin.name, null} 
data_dir: ${dir.dataset}/dataset
filetype: ${oc.select:.builtin.filetype, null}
autoload: true
verbose: ${oc.select:..verbose, true}
column_info:
  keys:
    id: id
  data:
use_name_as_subdir: true
