defaults:
  - feature
  - /pipeline: _build_feature

auto:
  build: true
info:
  data_dir: ${iif:${..use_name_as_subdir},${..data_dir}/${.name},${..data_dir}}
pipeline:
  name: ${oc.select:..name, null}
  output_dir: ${iif:${..use_name_as_subdir},${..data_dir}/${.name},${..data_dir}}
  split_sampling:
    dev_size:
    test_size: 0.2
