defaults:
  - default

_target_: ekorpkit.datasets.loader.Datasets
name: 
data_dir: ${dir.dataset}/simple
column_info:
  keys:
    id: id
  data:
autorun:
  - load
  - name: concatenate
    args:
      append_dataset_name: true
