_target_: ekorpkit.preprocessors.segmenter.PySBDSegmenter
language: en
clean: false
in_segment_separator: '\n\n'
in_sentence_separator: '\n'
out_segment_separator: '\n\n'
out_sentence_separator: '\n'
return_type: str
keep_segment: true
merge_lines: true
merge_level: segment
empty_lines_threshold: 0.6
broken_lines_threshold: 0.4
detection_level: segment
filter_programming_language: true
filter_sentence_length: true
min_num_words: 3
min_length: 10
verbose: false
print_args: true