_target_: ekorpkit.preprocessors.segmenter.PySBDSegmenter
language: en
clean: false
in_segment_separator: '\n\n'
in_sentence_separator: '\n'
out_segment_separator: '\n\n'
out_sentence_separator: '\n'
return_type: str
print_args: true
merge_lines: true
merge_level: article
filter_sentence_length: true
min_num_words: 3
min_length: 10
