name: model
data_dir: ${oc.select:..data_dir, ${dir.project}/data}
output_dir: ${oc.select:..output_dir, ${dir.output}/${.name}}
num_workers: ${oc.select:num_workers,1}
verbose: ${oc.select:..verbose, true}
