agg_method:
  mean:
    num_examples: num_examples
    agg:
      feature: mean
    score: feature
  median:
    num_examples: num_examples
    agg:
      feature: median
    score: feature
  diffusion:
    num_examples: num_examples
    eval:
      _pos: feature == 'positive'
      _neg: feature == 'negative'
    agg:
      _pos: sum
      _neg: sum
    score: (_pos - _neg) / (_pos + _neg + @eps)
