_default_:
  num_examples: num_examples
  agg:
    feature: mean
  score: feature
polarity:
  num_examples: num_examples
  agg:
    polarity: mean
  score: polarity
  labels:
    negative: (-1, -0.2)
    neutral: (-0.2, 0.2)
    positive: (0.2, 1)
