defaults:
  - ngram: default
  - score_function: npmi
  - scores: default
  - candidates: default
  - postag: default
  - /data: concat
  - /preprocessor/tokenizer: simple

_target_: ekorpkit.models.ngram.base.Ngrams
name: ngram
autoload: true
force_train: false
analyze:
  exclude_overlaps: true
  threshold:
ngramize:
  delimiter: ""
  strip_pos: true

progress_per: 1000
verbose: ${oc.select:..verbose,false}
