defaults:
  - score_function: pmi
  - candidates: default
  - postag: default
  - /data: concat
  - /preprocessor/tokenizer: simple

_target_: ekorpkit.models.ngram.base.Ngrams
name: ngram
force_train: false
analyze:
  exclude_overlaps: true
  threshold:
ngram:
  max_n: 5
  # The maximum window must be larger than ngram length n.
  max_window: ${.max_n}
  max_skip:
  delimiter: ;
ngramize:
  delimiter: ""
  strip_pos: true
output_dir: ${dir.project}/outputs/ngrams/
output_file: ${.name}_${.score_function.name}_model.parquet
progress_per: 1000
verbose: ${oc.select:..verbose,false}
