defaults:
  - /auto: default
  - /batch: default
  - /secret: default
  - /project: language-modeling
  - /path: _batch_
  - /dataset: language-modeling
  - /model: transformer.mlm
  - /tokenizer: pretrained
  - /training: transformer.mlm

_target_: ekorpkit.models.transformer.trainers.MlmTrainer
name: mlm-trainer
verbose: ${oc.select:..verbose, false}
use_accelerator: false
