defaults:
  - article_features: default
  - /_predict_: sentiment

_target_: ekorpkit.models.sentiment.base.SentimentAnalyser
name:
num_workers: ${oc.select:..num_workers,1}
use_batcher: ${oc.select:..use_batcher, true}
verbose: ${oc.select:..verbose, true}
