defaults:
  - /preprocessor/tokenizer: nltk
  - lexicon: hiv4

_target_: ekorpkit.models.sentiment.analyser.HIV4SA
name: hiv4sa
features:
  polarity:
    labels:
      negative: (-1, -0.2)
      neutral: (-0.2, 0.2)
      positive: (0.2, 1)
    lexicon_features:
      - Positiv
      - Negativ
predict:
  features: polarity
preprocessor:
  tokenizer:
    tokenize:
      concat_surface_and_pos: false
    nltk:
      lemmatize: false
      stem: false
