ARG BUILD_FROM="entelecheia/ekorpkit:latest-pytorch1.11-runtime"
FROM $BUILD_FROM

RUN apt-get update \
    && apt-get install -y --fix-missing openssh-server nodejs npm\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up locale
RUN localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true
# Update nodejs
RUN npm cache clean -f && npm install -g n && n lts

# Set up jupyter notebook extensions
RUN pip install --no-cache-dir --upgrade \
    jupyter_nbextensions_configurator ipywidgets RISE \
    jupyterlab \
    jupyterlab_execute_time \
    jupyterlab-git \
    jupyterlab-vim \
    jupytext \
    ipympl \
    ipython-autotime


RUN jupyter nbextension enable --py widgetsnbextension
RUN jupyter nbextensions_configurator enable
RUN jupyter labextension install \
    @jupyter-widgets/jupyterlab-manager \
    jupyterlab-slide-mode-keyboard-shortcuts \
    jupyter-matplotlib \
    jupyterlab-spreadsheet

# install dotfiles
ARG USER_FULLNAME=""
ARG USER_EMAIL=""
ARG GITHUB_USERNAME=""
ARG WORKSPACE_LOCATION="/"
ARG SYSTEM_HOSTNAME="ekorpkit-container"

ENV USER_FULLNAME $USER_FULLNAME
ENV USER_EMAIL $USER_EMAIL
ENV GITHUB_USERNAME $GITHUB_USERNAME
ENV WORKSPACE_LOCATION $WORKSPACE_LOCATION
ENV SYSTEM_HOSTNAME $SYSTEM_HOSTNAME
ENV APPLY_ROOTMOI=0
ENV REMOTE_CONTAINERS=1
# ENV DOTFILES_DEBUG=1
RUN rm -rf /workspace && mkdir -p /workspace
RUN sh -c "$(wget -qO- https://bit.ly/3W2JGyL)"
# Set up environment variables
ARG EKORPKIT_SRC_DIR="/workspace/projects/ekorpkit"
ENV EKORPKIT_SRC_DIR $EKORPKIT_SRC_DIR
WORKDIR $EKORPKIT_SRC_DIR

# install requirements
RUN pip install --no-cache-dir -e ".[all]"
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY ./scripts/devenv-entrypoint.sh ./scripts
RUN chmod 755 ./scripts/devenv-entrypoint.sh
CMD ["zsh"]
