version: '3'

services:
  workspace:
    build:
      context: .
      dockerfile: .docker/Dockerfile.devenv
      args:
        BUILD_FROM: $BUILD_FROM
        USER_FULLNAME: $USER_FULLNAME
        USER_EMAIL: $USER_EMAIL
        GITHUB_USERNAME: $GITHUB_USERNAME
        WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
        WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
        SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
        EKORPKIT_SRC_DIR: $EKORPKIT_SRC_DIR
        USERNAME: $USERNAME
        USER_UID: $USER_UID
        USER_GID: $USER_GID
    image: $IMAGE_NAME
    hostname: $CONTAINER_HOSTNAME
    command:
      - bash 
      - ./scripts/devenv-entrypoint.sh
    environment:
      HOST_JUPYTER_IP: $HOST_JUPYTER_IP
      HOST_JUPYTER_PORT: $HOST_JUPYTER_PORT
      JUPYTER_TOKEN: $JUPYTER_TOKEN
      JUPYTER_PORT: $JUPYTER_PORT
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
    ulimits:
      stack: 67108864
      memlock: -1
    ipc: host
    ports:
      - "$HOST_SSH_PORT:22"
      - "$HOST_JUPYTER_PORT:$JUPYTER_PORT"
      - "$HOST_RUBRIX_PORT:6900"
    volumes:
        - "$HOME/.ssh:/home/$USERNAME/.ssh"
        - "$HOME/.password-store:/home/$USERNAME/.password-store"
        - "$HOME/.passage:/home/$USERNAME/.passage"
        - "$HOME/.cache/huggingface:/home/$USERNAME/.cache/huggingface"
        - "$HOME/.huggingface:/home/$USERNAME/.huggingface"
        - "$WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT"
        - "$PWD/.resources/rubrix/.users.yaml:$RUBRIX_LOCAL_AUTH_USERS_DB_FILE"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${CUDA_DEVICE_ID}"]
              capabilities: [gpu]
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4840
    environment:
      NGROK_AUTH: $NGROK_AUTH
      NGROK_PORT: $NGROK_PORT
      NGROK_PROTOCOL: $NGROK_PROTOCOL
    depends_on:
      - workspace
networks:
  default:
    name: $DOCKER_NETWORK_NAME
    external: true
