# @package _global_
defaults:
  - _self_
  - about: __init__
  - mode: __init__
  - task: __init__

  - override hydra/help: help
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

HYFI_PACKAGE_CONFIG_PATH: ${oc.env:HYFI_PACKAGE_CONFIG_PATH,${__search_package_path__:}}
HYFI_USER_CONFIG_PATH: ${oc.env:HYFI_USER_CONFIG_PATH,${check_path:./conf,pkg://ekorpkit/hyfi/conf}}
hydra:
  searchpath:
    - ${HYFI_PACKAGE_CONFIG_PATH}
    - ${HYFI_USER_CONFIG_PATH}
