defaults:
  - _train
  - config: classification

_target_: ekorpkit.models.transformer.SimpleTrainerClassification
model_class: classification
labels: ${oc.select:dataset.labels, null}
num_labels:
use_cuda: true
cuda_device: -1
to_train:
  labels: labels
  text: text
to_predict:
  input: text
  predicted: pred_labels
