defaults:
  - _default
  - config: t5
  - /_keys_: simple_t5_classification
  - /_train_: simple_t5_classification
  - /_predict_: simple_t5_classification
  - /model/eval: simple_t5_classification

_target_: ekorpkit.models.transformer.SimpleT5
model_class: classification
cuda_device: 0
labels: ${oc.select:dataset.labels, null}
model:
  output_dir: ${..pred_output_dir}
  labels: ${..labels}
