# @package _global_
debug_mode: false
print_config: false
print_resolved_config: false
num_workers: 2
verbose: false
ignore_warnings: true

hydra:
  job:
    name: ${project}
  run:
    dir: ${dir.log}/hydra/${hydra.job.name}/${now:%Y-%m-%d}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${dir.log}/hydra/${hydra.job.name}/multiruns/${now:%Y-%m-%d}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
