# @package _global_
app_name: ${about.app.name}
name: ${project.name}
debug_mode: false
print_config: false
print_resolved_config: true
num_workers: ${alt:${oc.env:NUM_WORKERS,null},1}
verbose: false
ignore_warnings: true

hydra:
  job:
    name: ${project.name}
    chdir: true
  run:
    dir: ${dir.log}/hydra/${hydra.job.name}/${now:%Y-%m-%d}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${dir.log}/hydra/${hydra.job.name}/multiruns/${now:%Y-%m-%d}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  verbose: false
  job_logging:
    handlers:
      console:
        level: ${hydra.job_logging.root.level}
      file:
        level: ${hydra.job_logging.root.level}
    root:
      level: ${oc.env:EKORPKIT_LOG_LEVEL,INFO}
