batch_name: ${oc.select:..name,demo-batch}
batch_num:
output_dir: ${oc.select:..path.output_dir,null}
random_seed: true
seed:
resume_run: false
resume_latest: false
run_to_resume: latest
verbose: ${oc.select:verbose,false}
num_workers: ${oc.select:num_workers,1}
device: cpu
num_devices:
