defaults:
  - /batch: default
  - /project: language-modeling
  - /path: _batch_
  - /features: corpus
  - /io: _build_corpus
  - /info: _build_corpus
  - /pipeline: _build_corpus
  - /auto: load

_target_: ekorpkit.datasets.build.DatasetBuilder
name:
path:
  data_dir: ${.corpus}/${..name}
filetype: .parquet

pipeline:
  normalize:
    preprocessor:
      normalizer: ${oc.select:corpus.builtin.preprocessor.normalizer,null}
  segment:
    preprocessor:
      segmenter: ${oc.select:corpus.builtin.preprocessor.segmenter,null}
