defaults:
  - _default

_target_: ekorpkit.io.fetch.loader.glassdoor.GlassDoor
output_file: ${.name}.jl
input_file: ${dir.dataset}/source/byod/gd/reviews.tar
file_extension: .htm
verbose: true
print_every_n: 1000
