_target_: ekorpkit.visualize.classification.plot_confusion_matrix
confusion_matrix:
# confusion matrix to be passed in
display_labels: auto
# List of strings containing the display_labels to be displayed on the x,y axis. Default is 'auto'
matrix_labels:
# List of strings that represent the labels row by row to be shown in each square.
include_values: true
# If True, show the raw number in the confusion matrix. Default is True.
include_percentages: true
# If True, show the proportions for each category. Default is True.
summary_stats: true
# If True, display summary statistics below the figure. Default is True.
cbar: true
# If True, show the color bar. The cbar values are based off the values in the confusion matrix.
# Default is True.
cmap: Blues
# Colormap of the values displayed from matplotlib.pyplot.cm. Default is 'Blues'
output_dir: ${oc.select:..output_dir, .}
output_file: ${oc.select:..output_file, cm.png}
verbose: ${oc.select:verbose, true}
savefig:
  fname: ${..output_dir}/${..output_file}
  dpi: 300
plot:
  figsize: (10, 5)
  style: fivethirtyeight
  fontpath:
  rcParams:
    axes.unicode_minus: False
    axes.labelsize: 14
    text.color: dimgrey
    font.family: NanumGothic
figure:
  xlabel:
    xlabel: Predicted label
  ylabel:
    ylabel: Actual label
  title:
    label:

  #  cm:            confusion matrix to be passed in

  #   group_names:   List of strings that represent the labels row by row to be shown in each square.

  #   categories:    List of strings containing the categories to be displayed on the x,y axis. Default is 'auto'

  #   count:         If True, show the raw number in the confusion matrix. Default is True.

  #   percent:       If True, show the proportions for each category. Default is True.

  #   cbar:          If True, show the color bar. The cbar values are based off the values in the confusion matrix.
  #                  Default is True.

  #   xyticks:       If True, show x and y ticks. Default is True.

  #   xyplotlabels:  If True, show 'True Label' and 'Predicted Label' on the figure. Default is True.

  #   sum_stats:     If True, display summary statistics below the figure. Default is True.

  #   figsize:       Tuple representing the figure size. Default will be the matplotlib rcParams value.

  #   cmap:          Colormap of the values displayed from matplotlib.pyplot.cm. Default is 'Blues'
  #                  See http://matplotlib.org/examples/color/colormaps_reference.html

  #   title:         Title for the heatmap. Default is None.
