defaults:
  - /path: data_output
  - /visualize/plot: confusion_matrix
  - /_func_: evaluate_classification_performance

_target_: ekorpkit.models.eval.eval_classification
data:
data_dir:
data_file:
function:
  average: weighted
  labels: ${..labels}
output_dir: ${oc.select:..output_dir, .}
output_file: ${oc.select:..output_file, confusion_matrix.png}
labels: ${..labels}
visualize:
  output_dir: ${..output_dir}
  output_file: ${..output_file}
  labels: ${..labels}
  plot:
    labels: ${..labels}
    confusion_matrix:
      display_labels: ${..labels}
verbose: ${oc.select:..verbose, false}
