name: markdown-autodocs

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'docs/**'
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.4
          with:
            output_file_paths: '[./README.md,./docs/corpus/info/*.md,./docs/dataset/t5/info/*.md,./docs/cli/*.md]'

