name: test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install-windows
        if: runner.os == 'Windows'
        run: |
          pip install -e ".[all]"
          pip install -r requirements-test.txt

      - name: Install-others
        if: runner.os != 'Windows'
        run: |
          pip install -e .\[all\]
          pip install -r requirements-test.txt

      - name: Run tests
        run: pytest tests

      - name: "Upload coverage to codecov"
        uses: codecov/codecov-action@v1
