name: test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [main]
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  #     - reopened
  #   branches:    
  #     - 'release/**'
  #     - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: install dependencies
        run: |
          pip install -e ".[all]"
          pip install -r requirements-test.txt

      - name: Run tests
        run: pytest -m "not local and not gpu"

      - name: "Upload coverage to codecov"
        uses: codecov/codecov-action@v3
        with:
          files: test_results/coverage/coverage.xml
