defaults:
  - /method: predict

name: predict
model:
output_dir: ${oc.select:..output_dir, ${dir.output}/${.name}}
output_file: ${oc.select:..output_file, null}
num_workers: ${oc.select:..num_workers,1}
use_batcher: ${oc.select:..use_batcher, true}
verbose: ${oc.select:..verbose, true}
